@startuml Principal
hide empty members
hide circle
skinparam shadowing false
skinparam classAttributeIconSize 0
class Principal <<struct>> {
  + UserID : int
  + Name : string
  + Role : Role
}
@enduml
