@startuml CommuteResponse
hide empty members
hide circle
skinparam shadowing false
skinparam classAttributeIconSize 0
class CommuteResponse <<struct>> {
  + SourceBranch : int (optional)
  + DestinationBranch : int (optional)
  + CommuteTime : int
}
@enduml
