@startuml Booking
hide empty members
hide circle
skinparam shadowing false
skinparam classAttributeIconSize 0
class Booking <<struct>> {
  + ID : int
  + TeacherID : int
  + TeacherName : string
  + BranchID : int
  + BranchName : string
  + SubjectID : int
  + SubjectName : string
  + StartTime : time.Time
  + EndTime : time.Time
  + StudentID : int
  + StudentName : string
  + CreatedAt : time.Time
}
@enduml
