@startuml Assignment
hide empty members
hide circle
skinparam shadowing false
skinparam classAttributeIconSize 0
class Assignment <<struct>> {
  + Values : map[string]int
  + Metadata : map[string]any
}
@enduml
