// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/availability": {
            "get": {
                "description": "Returns all active teachers with their weekly availability slots, grouped by teacher",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "availability"
                ],
                "summary": "Get all teacher availability",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TeacherAvailability"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Replaces all existing availability for a teacher with the provided weekly schedule (full replace, not merge). Rejects overlapping slots within the same day.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "availability"
                ],
                "summary": "Submit weekly availability",
                "parameters": [
                    {
                        "description": "Weekly availability payload. day_of_week: 0=Monday through 6=Sunday",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AvailabilityPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings": {
            "post": {
                "description": "Evaluates each preferred_slot independently and returns per-slot results with either an exact_match or alternatives.\n\n**Required fields:**\n- ` + "`" + `subject_id` + "`" + ` (int): The subject to book. Must be positive.\n- ` + "`" + `branch_id` + "`" + ` (int): The branch location. Must be positive.\n- ` + "`" + `preferred_slots` + "`" + ` (array): One or more time windows. Each slot has:\n- ` + "`" + `day_of_week` + "`" + `: 0=Monday through 6=Sunday\n- ` + "`" + `start` + "`" + `: Time in HH:MM format (e.g. \"09:00\")\n- ` + "`" + `end` + "`" + `: Time in HH:MM format, must be after start\n\n**Optional fields:**\n- ` + "`" + `duration_minutes` + "`" + ` (int): Session length. When omitted or 0, the full window (end - start) is used as the session duration. When set, candidates are generated in 30-minute steps within the window matching this duration.\n- ` + "`" + `preferred_teacher_id` + "`" + ` (int): Prioritize a specific teacher. When omitted, all teachers scored neutrally (+20). When set, matching teacher gets +40, others +0.\n\n**Response:** ` + "`" + `results[]` + "`" + ` has one entry per slot, in request order. Each entry has either ` + "`" + `exact_match` + "`" + ` (score=100, teacher fully matches) or ` + "`" + `alternatives` + "`" + ` (up to 3, ranked by score 0-100).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Evaluate a booking request",
                "parameters": [
                    {
                        "description": "Booking request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BookingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BookingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/confirm": {
            "post": {
                "description": "Creates the actual booking in the database after the client selects a result from the evaluate endpoint.\n\n**Required fields:**\n- ` + "`" + `teacher_id` + "`" + ` (int): The teacher assigned to the booking.\n- ` + "`" + `branch_id` + "`" + ` (int): The branch location.\n- ` + "`" + `subject_id` + "`" + ` (int): The subject to book.\n- ` + "`" + `start_time` + "`" + ` (RFC3339): Start time of the booking (use the value directly from the evaluate response).\n- ` + "`" + `end_time` + "`" + ` (RFC3339): End time of the booking (use the value directly from the evaluate response).\n- ` + "`" + `client_name` + "`" + ` (string): Name of the client making the booking.\n\n**Constraints:** Overlapping bookings for the same teacher are rejected (409 Conflict) via EXCLUDE gist constraint.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Confirm a booking",
                "parameters": [
                    {
                        "description": "Booking confirmation",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ConfirmBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Booking"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/{id}": {
            "delete": {
                "description": "Deletes a confirmed booking by ID. Returns 404 if not found.",
                "tags": [
                    "bookings"
                ],
                "summary": "Cancel a booking",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Booking ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/branches": {
            "get": {
                "description": "Returns all branches ordered by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "List branches",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Branch"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subjects": {
            "get": {
                "description": "Returns all subjects ordered by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subjects"
                ],
                "summary": "List subjects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Subject"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teachers": {
            "get": {
                "description": "Returns all teachers with active status, ordered by name. Optionally filter by subject_id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "List active teachers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by subject ID",
                        "name": "subject_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Teacher"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AvailabilityPayload": {
            "type": "object",
            "properties": {
                "teacher_id": {
                    "type": "integer",
                    "example": 42
                },
                "weekly": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WeeklySlot"
                    }
                }
            }
        },
        "models.Booking": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "client_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "integer"
                },
                "teacher_id": {
                    "type": "integer"
                }
            }
        },
        "models.BookingAlternative": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "commute_minutes": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "reasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "room_available": {
                    "type": "boolean"
                },
                "score": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "integer"
                },
                "teacher_id": {
                    "type": "integer"
                },
                "teacher_name": {
                    "type": "string"
                }
            }
        },
        "models.BookingRequest": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer",
                    "example": 1
                },
                "duration_minutes": {
                    "type": "integer",
                    "example": 60
                },
                "preferred_slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WeeklySlot"
                    }
                },
                "preferred_teacher_id": {
                    "type": "integer",
                    "example": 5
                },
                "subject_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.BookingResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SlotResult"
                    }
                }
            }
        },
        "models.Branch": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.ConfirmBookingRequest": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer",
                    "example": 1
                },
                "client_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "end_time": {
                    "type": "string",
                    "example": "2026-06-01T10:00:00Z"
                },
                "start_time": {
                    "type": "string",
                    "example": "2026-06-01T09:00:00Z"
                },
                "subject_id": {
                    "type": "integer",
                    "example": 1
                },
                "teacher_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "failed to retrieve teachers"
                }
            }
        },
        "models.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Availability saved successfully"
                }
            }
        },
        "models.SlotResult": {
            "type": "object",
            "properties": {
                "alternatives": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BookingAlternative"
                    }
                },
                "exact_match": {
                    "$ref": "#/definitions/models.BookingAlternative"
                },
                "message": {
                    "type": "string"
                },
                "slot": {
                    "$ref": "#/definitions/models.WeeklySlot"
                }
            }
        },
        "models.Subject": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Teacher": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "alice@example.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Alice"
                }
            }
        },
        "models.TeacherAvailability": {
            "type": "object",
            "properties": {
                "teacher": {
                    "$ref": "#/definitions/models.Teacher"
                },
                "weekly": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WeeklySlot"
                    }
                }
            }
        },
        "models.WeeklySlot": {
            "type": "object",
            "properties": {
                "day_of_week": {
                    "description": "0=Monday ... 6=Sunday",
                    "type": "integer",
                    "example": 0
                },
                "end": {
                    "type": "string",
                    "example": "10:00"
                },
                "start": {
                    "type": "string",
                    "example": "09:00"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Converge API",
	Description:      "API for teacher availability management and bookings",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
