// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/availability": {
            "get": {
                "description": "Returns all active teachers with their weekly availability slots, grouped by teacher",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "availability"
                ],
                "summary": "Get all teacher availability",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/teacher.TeacherAvailability"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Replaces all existing availability for a teacher with the provided weekly schedule (full replace, not merge). Rejects overlapping slots within the same day.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "availability"
                ],
                "summary": "Submit weekly availability",
                "parameters": [
                    {
                        "description": "Weekly availability payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/scheduling.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings": {
            "get": {
                "description": "Returns all bookings sorted by creation date descending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "List all confirmed bookings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/scheduling.Booking"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Evaluates each preferred_slot independently and returns per-slot results with either an exact_match or alternatives.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Evaluate a booking request",
                "parameters": [
                    {
                        "description": "Booking request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scheduling.BookingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduling.BookingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/confirm": {
            "post": {
                "description": "Creates the actual booking in the database after the client selects a result from the evaluate endpoint.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Confirm a booking",
                "parameters": [
                    {
                        "description": "Booking confirmation",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scheduling.ConfirmBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/scheduling.Booking"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/{id}": {
            "delete": {
                "description": "Deletes a confirmed booking by ID. Returns 404 if not found.",
                "tags": [
                    "bookings"
                ],
                "summary": "Cancel a booking",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Booking ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduling.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/branches": {
            "get": {
                "description": "Returns all branches ordered by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "branches"
                ],
                "summary": "List branches",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/branch.Branch"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subjects": {
            "get": {
                "description": "Returns all subjects ordered by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subjects"
                ],
                "summary": "List subjects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/shared.Subject"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teachers": {
            "get": {
                "description": "Returns all teachers with active status, ordered by name. Optionally filter by subject_id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "List active teachers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by subject ID",
                        "name": "subject_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/teacher.Teacher"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a new teacher with name, email, and gender",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "Create a teacher",
                "parameters": [
                    {
                        "description": "New teacher payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teacher.CreateTeacherRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/teacher.Teacher"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teachers/{id}/gender": {
            "patch": {
                "description": "Sets a teacher's gender to male, female, or lgbtq+",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "Update a teacher's gender",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Teacher ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New gender",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teacher.UpdateGenderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduling.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teachers/{id}/status": {
            "patch": {
                "description": "Sets a teacher's status to active or deactivated",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "Toggle teacher active/deactivated status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Teacher ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teacher.UpdateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduling.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/scheduling.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "branch.Branch": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer",
                    "example": 30
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Siam"
                }
            }
        },
        "scheduling.Booking": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "client_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "integer"
                },
                "teacher_id": {
                    "type": "integer"
                }
            }
        },
        "scheduling.BookingAlternative": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "commute_minutes": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "reasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "score": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "integer"
                },
                "teacher_id": {
                    "type": "integer"
                },
                "teacher_name": {
                    "type": "string"
                }
            }
        },
        "scheduling.BookingRequest": {
            "type": "object",
            "required": [
                "branch_id",
                "preferred_slots",
                "required_gender",
                "subject_id"
            ],
            "properties": {
                "branch_id": {
                    "type": "integer",
                    "example": 1
                },
                "duration_minutes": {
                    "type": "integer",
                    "example": 60
                },
                "preferred_slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/shared.WeeklySlot"
                    }
                },
                "preferred_teacher_id": {
                    "type": "integer",
                    "example": 5
                },
                "required_gender": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female",
                        "lgbtq+"
                    ],
                    "example": "female"
                },
                "subject_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "scheduling.BookingResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scheduling.SlotResult"
                    }
                }
            }
        },
        "scheduling.ConfirmBookingRequest": {
            "type": "object",
            "required": [
                "branch_id",
                "client_name",
                "end_time",
                "start_time",
                "subject_id",
                "teacher_id"
            ],
            "properties": {
                "branch_id": {
                    "type": "integer",
                    "example": 1
                },
                "client_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "end_time": {
                    "type": "string",
                    "example": "2026-06-01T10:00:00Z"
                },
                "start_time": {
                    "type": "string",
                    "example": "2026-06-01T09:00:00Z"
                },
                "subject_id": {
                    "type": "integer",
                    "example": 1
                },
                "teacher_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "scheduling.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "failed to retrieve teachers"
                }
            }
        },
        "scheduling.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Availability saved successfully"
                }
            }
        },
        "scheduling.SlotResult": {
            "type": "object",
            "properties": {
                "alternatives": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scheduling.BookingAlternative"
                    }
                },
                "exact_match": {
                    "$ref": "#/definitions/scheduling.BookingAlternative"
                },
                "message": {
                    "type": "string"
                },
                "slot": {
                    "$ref": "#/definitions/shared.WeeklySlot"
                }
            }
        },
        "shared.Subject": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "shared.WeeklySlot": {
            "type": "object",
            "properties": {
                "day_of_week": {
                    "description": "0=Sunday ... 6=Saturday (matches JavaScript Date.getDay())",
                    "type": "integer",
                    "example": 0
                },
                "end": {
                    "type": "string",
                    "example": "10:00"
                },
                "start": {
                    "type": "string",
                    "example": "09:00"
                }
            }
        },
        "teacher.CreateTeacherRequest": {
            "type": "object",
            "required": [
                "email",
                "gender",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "alice@example.com"
                },
                "gender": {
                    "type": "string",
                    "example": "female"
                },
                "name": {
                    "type": "string",
                    "example": "Alice"
                }
            }
        },
        "teacher.Teacher": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "alice@example.com"
                },
                "gender": {
                    "type": "string",
                    "example": "female"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Alice"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "teacher.TeacherAvailability": {
            "type": "object",
            "properties": {
                "teacher": {
                    "$ref": "#/definitions/teacher.Teacher"
                },
                "weekly": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/shared.WeeklySlot"
                    }
                }
            }
        },
        "teacher.UpdateGenderRequest": {
            "type": "object",
            "required": [
                "gender"
            ],
            "properties": {
                "gender": {
                    "type": "string",
                    "example": "female"
                }
            }
        },
        "teacher.UpdateStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "example": "deactivated"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Converge API",
	Description:      "API for teacher availability management and bookings",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
